### ISSUE TITLE
Add targeted data gathering

### ISSUE THREAD

**Issue by aufi** [konveyor/forklift-must-gather#3]
In order to allow users to debug migrations, it is needed to add targeted data gathering (logs, CRs) for must-gather.

Supported use-cases
1. gather details for a migration Plan (logs, CRs)
2. by NAMESPACE, PLAN, VM?

Example commands
```
oc adm must-gather --image=quay.io/konveyor/forklift-must-gather:latest -- NS=<NS> PLAN=<PLAN> VM=<VM> /usr/bin/gather
```

**Comment by fdupont-redhat** [comment]
See: https://issues.redhat.com/browse/MTV-31

**Comment by aufi** [comment]
How the must-gather is executed from CLI https://github.com/openshift/oc/blob/master/pkg/cli/admin/mustgather/mustgather.go

**Comment by aufi** [comment]
Ther PR was merged, basic requested targeted gathering functionality works. Closing the issue.

Anyway I'm ready to incorporate a feedback on targeted must-gather usage or possible bugs whenever it appears.
